import numpy as num
m1 = num.array([[5, 8], [10, 12]])
m2 = num.array([[4, 3], [7, 9]])
print("First matrix : ", m1)
print("Second matrix : ", m2)
addition= num.add(m1,m2)
print("Addition of matrices is: ", addition)
Difference=num.subtract(m1,m2)
print("Difference of matrix is: ",Difference)
Division=num.divide(m1,m2)
print("Matrix after division: ",Division)
product=num.multiply(m1,m2)
print("Product of matrix is: ",product)
squarerootm1=num.sqrt(m1)
print("Square root of first matrix is: ",squarerootm1)
squarerootm2=num.sqrt(m2)
print("Squareroot of second matrix is: ",squarerootm2)
sum1=num.sum(m1)
print("Sum of first matrix m1 is: ",sum1)
sum2=num.sum(m2)
print("sum of second matrix m2 is: ",sum2)
dot=num.dot(m1,m2)
print("Matrix after dot operation: ",dot)
print("transpose of matrix m1 is: ",m1.T)
print("transpose of second matrix is: ",m2.T)